/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/pipes/pipes.module';
class PipesModuleInjector extends import0.ɵNgModuleInjector<import1.PipesModule> {
  _PipesModule_0:import1.PipesModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.PipesModule {
    this._PipesModule_0 = new import1.PipesModule();
    return this._PipesModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.PipesModule)) { return this._PipesModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const PipesModuleNgFactory:import0.NgModuleFactory<import1.PipesModule> = new import0.NgModuleFactory<any>(PipesModuleInjector,import1.PipesModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21hYy93b3JrL2lvbmljLWFscGhhLXNjcm9sbC9zcmMvcGlwZXMvcGlwZXMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL21hYy93b3JrL2lvbmljLWFscGhhLXNjcm9sbC9zcmMvcGlwZXMvcGlwZXMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
