/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/modules/alpha-scroll.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from 'ionic-angular/module';
import * as import5 from '../../../src/pipes/pipes.module';
import * as import6 from '../../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as import7 from '../../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as import8 from '../../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as import9 from '../../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as import10 from '../../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as import11 from '../../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/select/select-popover-component.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
class ScrollModuleInjector extends import0.ɵNgModuleInjector<import1.ScrollModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ReactiveFormsModule_3:import3.ReactiveFormsModule;
  _IonicModule_4:import4.IonicModule;
  _PipesModule_5:import5.PipesModule;
  _ScrollModule_6:import1.ScrollModule;
  __NgLocalization_7:import2.NgLocaleLocalization;
  __ɵi_8:import3.ɵi;
  __FormBuilder_9:import3.FormBuilder;
  constructor(parent:import0.Injector) {
    super(parent,[
      import6.ActionSheetCmpNgFactory,
      import7.AlertCmpNgFactory,
      import8.IonicAppNgFactory,
      import9.LoadingCmpNgFactory,
      import10.ModalCmpNgFactory,
      import11.PickerCmpNgFactory,
      import12.PopoverCmpNgFactory,
      import13.SelectPopoverNgFactory,
      import14.ToastCmpNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_7():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_7 == null)) { (this.__NgLocalization_7 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_7;
  }
  get _ɵi_8():import3.ɵi {
    if ((this.__ɵi_8 == null)) { (this.__ɵi_8 = new import3.ɵi()); }
    return this.__ɵi_8;
  }
  get _FormBuilder_9():import3.FormBuilder {
    if ((this.__FormBuilder_9 == null)) { (this.__FormBuilder_9 = new import3.FormBuilder()); }
    return this.__FormBuilder_9;
  }
  createInternal():import1.ScrollModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ReactiveFormsModule_3 = new import3.ReactiveFormsModule();
    this._IonicModule_4 = new import4.IonicModule();
    this._PipesModule_5 = new import5.PipesModule();
    this._ScrollModule_6 = new import1.ScrollModule();
    return this._ScrollModule_6;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_3; }
    if ((token === import4.IonicModule)) { return this._IonicModule_4; }
    if ((token === import5.PipesModule)) { return this._PipesModule_5; }
    if ((token === import1.ScrollModule)) { return this._ScrollModule_6; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_7; }
    if ((token === import3.ɵi)) { return this._ɵi_8; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_9; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ScrollModuleNgFactory:import0.NgModuleFactory<import1.ScrollModule> = new import0.NgModuleFactory<any>(ScrollModuleInjector,import1.ScrollModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21hYy93b3JrL2lvbmljLWFscGhhLXNjcm9sbC9zcmMvbW9kdWxlcy9hbHBoYS1zY3JvbGwubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL21hYy93b3JrL2lvbmljLWFscGhhLXNjcm9sbC9zcmMvbW9kdWxlcy9hbHBoYS1zY3JvbGwubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
